ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 14

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

# startx & starty: Top Left Coordinates!

# Example:
#[[structure]]
#name = "rplacede_schriftzug"
#file = "images/rplacede_schriftzug.png"
#startx = 0
#starty = 856
#priority = 3
